name: genera pk news

on:
#  push:
  repository_dispatch:
  schedule:
    - cron: "5 4 * * *"
#    - cron: "3 8-11 * * *"
#    - cron: "3 11-23/2 * * *"
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile scrape e mlr
      run: |-
        mkdir -p ~/bin
        cp bin/scrape ~/bin
        cp bin/mlr ~/bin
        cp bin/mlrgo ~/bin
        cd ~/bin
        chmod +x scrape
        chmod +x mlr
        chmod +x mlrgo
        sudo pip install yq
        cd ~/bin
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.398/quarto-1.4.398-linux-amd64.tar.gz
        tar -C ./ -xvzf quarto-1.4.398-linux-amd64.tar.gz
        ln -s ./quarto-1.4.398/bin/quarto ~/bin/quarto
    - name: esegui lo script
      run: |-
        export PATH=$PATH:~/bin
        cd ./pk/news/script/
        chmod +x ./news.sh
        ./news.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "aggiornamento news pk: ${timestamp}" || exit 0
        git push
